services:
    postgres:
      image: postgres:17.4-alpine3.21
      ports:
        - 5432:5432
      volumes:
        - ~/apps/health-monitor-apps:/var/lib/postgresql/data
        - ./database/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
        - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      environment:
         POSTGRES_USER: postgres
         POSTGRES_USERNAME: ${POSTGRES_USERNAME}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_HOST: ${POSTGRES_HOST}
         POSTGRES_DB: ${POSTGRES_DB}
