#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${POSTGRES_USERNAME} WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USERNAME};
	\c ${POSTGRES_DB}
	GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USERNAME" --dbname "$POSTGRES_DB" -f /docker-entrypoint-initdb.d/init.sql
